<?php
namespace app\components;

use yii\base\Widget;

class LeftMenuWidget extends Widget
{
    public $sections;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $sections = $this->sections;
        return $this->render('left-menu', compact('sections'));
    }
}