<?php

namespace app\components;


use yii\base\Widget;

class OneLevelMenuWidget extends Widget
{
    public $sectionMenu;
    public $urlActive;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $sectionMenu = $this->sectionMenu;
        $urlActive = $this->urlActive;
        return $this->render('one-level-menu', compact('sectionMenu', 'urlActive'));
    }
}