<?php
/**
 * Каталог Экола (миниатюры)
 */
namespace app\components;

use yii\base\Widget;

class ThumbnailCatalogWidget extends Widget
{
    public $template = 'list';
    public $dataTable;
    private $countItems;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->template = $this->template == 'table' ? 'table' : 'list';
        if ($this->dataTable) {
            //12-количество эл. сетки
            $this->countItems = 12 / count($this->dataTable);
        }
    }

    public function run()
    {
        return $this->render($this->template == 'list' ? 'thumbnail-list' : 'thumbnail-table',
            [
                'dataTable' => $this->dataTable,
                'countItems' => $this->countItems,
            ]
        );
    }

}