<?php
/**
 * Каталог Экола (миниатюры)
 */

use yii\base\Widget;

class ThumbnailCatalogWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('thumbnail-catalog');
    }
}